name: CI/CD & DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-secure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build Docker Image
        run: docker build -t my-app:${{ github.sha }} .

      # [DEVSECOPS] Jalankan Vulnerability Scanner (Trivy) pada Docker Image
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'my-app:${{ github.sha }}'
          format: 'table'
          exit-code: '0' # Ubah jadi '1' jika ingin pipeline gagal saat ditemukan celah keamanan kritis
          vuln-type: 'os,package'
          severity: 'CRITICAL,HIGH'
